# กำหนดเวอร์ชั่นของ Docker Compose
version: '3.8'

# กำหนด Services หรือ Containers ที่จะรัน
services:
  # Service ของ Backend API (ตอนนี้เหลือแค่ Service เดียว)
  api:
    # --- แก้ไขส่วน Build ---
    # เราเปลี่ยน context เป็น . (โฟลเดอร์โปรเจกต์ทั้งหมด)
    # และระบุ path ไปยัง Dockerfile ให้ถูกต้อง เพื่อให้ Docker หา package.json เจอ
    build:
      context: .
      dockerfile: Dockerfile
    
    container_name: icrud_api
    restart: unless-stopped
    ports:
      - "3000:3000"
      
    # --- แก้ไข Environment Variables ---
    # เราจะให้ Drizzle ใช้ Connection String จาก POSTGRES_URL ในไฟล์ .env โดยตรง
    environment:
      - POSTGRES_URL=${POSTGRES_URL} # <--- จุดสำคัญ: ดึง URL จาก .env มาใช้งาน
      - API_SECRET=${API_SECRET}
      
    # --- ลบส่วนที่เกี่ยวข้องกับ Service 'db' ทิ้ง ---
    # ลบ depends_on: db: เพราะไม่ต้องรอ container db อีกต่อไป
    # ลบ networks: เพราะไม่ต้องเชื่อมต่อกับ service อื่นใน network ภายในแล้ว

# --- ลบ Service 'db' ทิ้งทั้งหมด ---
# เราไม่ได้สร้าง container สำหรับฐานข้อมูลอีกต่อไป เพราะเราจะเชื่อมต่อไปยังฐานข้อมูลภายนอก
# ดังนั้นจึงลบบล็อกของ service 'db' ทั้งหมดที่เคยอยู่ตรงนี้ทิ้งไป

# --- ลบ Network และ Volume ที่ไม่จำเป็นแล้วทิ้งไป ---
# เนื่องจากไม่มี service 'db' แล้ว จึงไม่จำเป็นต้องกำหนด custom network หรือ volume อีก
